import { StyleSheet } from 'react-native';

const baseStyles = {
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  container: { flexGrow: 1, padding: 20, paddingBottom: 130 },
  header: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  headerContent: { flex: 1, minWidth: 0, paddingRight: 12 },
  eyebrow: { color: '#2563eb', fontSize: 10, fontWeight: '700', letterSpacing: 1.6, marginBottom: 5 },
  title: { color: '#111827', fontSize: 30, fontWeight: '800' },
  date: { flexShrink: 0, color: '#6b7280', fontSize: 13, marginTop: 7 },
  pageIntro: { marginBottom: 18 },
  pagePager: { flex: 1 },
  page: { flex: 1 },
  pageContainer: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 6, paddingBottom: 130 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionLabel: { color: '#6b7280', fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  progressPercent: { color: '#1d4ed8', fontSize: 12, fontWeight: '700' },
  progressTrack: { flexDirection: 'row', height: 10, backgroundColor: '#e5e7eb', borderRadius: 5, overflow: 'hidden', marginTop: 8, marginBottom: 6 },
  progressHalf: { flex: 1, overflow: 'hidden' },
  progressDivider: { width: 2, backgroundColor: '#ffffff' },
  progressValue: { height: '100%', borderRadius: 5 },
  tasksProgress: { backgroundColor: '#0891b2' },
  completionProgress: { backgroundColor: '#2563eb' },
  progressLegend: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 },
  progressLegendText: { color: '#6b7280', fontSize: 11 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  stat: { flex: 1, padding: 14, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8 },
  statLabel: { color: '#6b7280', fontSize: 10, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  statValue: { color: '#111827', fontSize: 22, fontWeight: '800', marginTop: 4 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sectionTitle: { color: '#111827', fontSize: 18, fontWeight: '800' },
  muted: { color: '#9ca3af', fontSize: 12 },
  card: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8, padding: 14, marginBottom: 24 },
  empty: { color: '#9ca3af', fontSize: 14, paddingVertical: 8 },
  taskRow: { flexDirection: 'row', alignItems: 'center', minHeight: 38, paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  checkbox: { width: 21, height: 21, borderWidth: 1.5, borderColor: '#9ca3af', borderRadius: 5, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  checked: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  checkmark: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
  taskText: { flex: 1, minWidth: 0, color: '#374151', fontSize: 15 },
  completed: { color: '#9ca3af', textDecorationLine: 'line-through' },
  workBoard: { marginBottom: 18, paddingVertical: 4 },
  addRoutinePanel: { backgroundColor: '#f8fafc', borderRadius: 12, padding: 14, marginBottom: 24 },
  addRoutineLabel: { color: '#374151', fontSize: 12, fontWeight: '800', letterSpacing: 0.4, marginBottom: 9 },
  themeToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12, marginBottom: 18 },
  themeToggleText: { flex: 1, minWidth: 0, paddingRight: 12 },
  delete: { color: '#9ca3af', fontSize: 21, paddingHorizontal: 5 },
  workScroller: { flexGrow: 0, flexShrink: 0 },
  workTable: { minWidth: 390 },
  workHeader: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#dbe4ef', minHeight: 32 },
  workNameHeader: { width: 130, color: '#64748b', fontSize: 9, fontWeight: '800', letterSpacing: 0.6 },
  dayHeader: { width: 32, color: '#4b5563', fontSize: 9, fontWeight: '700', textAlign: 'center' },
  workDeleteHeader: { width: 24 },
  workRow: { flexDirection: 'row', alignItems: 'center', minHeight: 42, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  workName: { width: 130, flexShrink: 1, color: '#374151', fontSize: 13 },
  workCheckboxCell: { width: 32, alignItems: 'center', justifyContent: 'center' },
  workCheckmark: { width: 16, height: 16, borderWidth: 1, borderColor: '#9ca3af', alignItems: 'center', justifyContent: 'center' },
  workCheckText: { color: '#9f6f7e', fontSize: 11, lineHeight: 14 },
  workChecked: { backgroundColor: '#f3e8ed', borderColor: '#9f6f7e' },
  workDelete: { width: 24, alignItems: 'center' },
  addWorkRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 14 },
  inlineInput: { flex: 1, height: 42, borderWidth: 1, borderColor: '#d1d5db', borderRadius: 6, paddingHorizontal: 10, color: '#111827', fontSize: 14 },
  rulesInput: { width: '100%', height: 52, borderWidth: 1, borderColor: '#9ca3af', borderRadius: 6, paddingHorizontal: 14, color: '#111827', backgroundColor: '#ffffff', fontSize: 20, fontWeight: '600', marginBottom: 16 },
  smallButton: { backgroundColor: '#eff6ff', borderRadius: 6, paddingHorizontal: 14, height: 42, justifyContent: 'center' },
  smallButtonText: { color: '#1d4ed8', fontWeight: '700' },
  goalRow: { flexDirection: 'row', alignItems: 'center',  maxHeight: 40, paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingHorizontal: 8, borderRadius: 5 },
  selectedGoal: { backgroundColor: '#eff6ff' },
  goalScroller: { flexGrow: 0, flexShrink: 0, height: 38 },
  goalChip: { flexDirection: 'row', alignItems: 'center', minHeight: 30, maxHeight: 34, borderWidth: 1, borderColor: '#5175bd', borderRadius: 6, paddingHorizontal: 10 },
  goalList: { alignItems: 'center', gap: 8, paddingBottom: 2 },
  goalDot: { width: 9, height: 9, borderRadius: 5, marginRight: 10 },
  goalText: { flexShrink: 1, maxWidth: 180, color: '#374151', fontSize: 15 },
  chevron: { color: '#9ca3af', fontSize: 24 },
  ruleLabel: { color: '#374151', fontSize: 13, fontWeight: '700', marginBottom: 7, marginTop: 4 },
  primaryButton: { backgroundColor: '#2563eb', borderRadius: 6, alignItems: 'center', paddingVertical: 13 },
  rulesButton: { marginTop: 14 },
  savedMessage: { color: '#15803d', fontSize: 13, fontWeight: '600', textAlign: 'center', marginTop: 10 },
  primaryButtonText: { color: '#ffffff', fontWeight: '700', fontSize: 15 },
  floatingButton: { position: 'absolute', right: 24, bottom: 104, width: 54, height: 54, borderRadius: 27, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', elevation: 4, shadowColor: '#2563eb', shadowOpacity: 0.3, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
  floatingPlus: { color: '#ffffff', fontSize: 30, fontWeight: '300', lineHeight: 32 },
  bottomNavShell: { position: 'absolute', left: 18, right: 18, bottom: 14, borderRadius: 24, overflow: 'hidden', shadowColor: '#111827', shadowOpacity: 0.16, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
  bottomNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', minHeight: 68, paddingHorizontal: 8, backgroundColor: 'rgba(255, 255, 255, 0.88)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.95)' },
  bottomNavItem: { flex: 1, alignItems: 'center', justifyContent: 'center', minHeight: 54, borderRadius: 18 },
  bottomNavItemActive: { backgroundColor: 'rgba(37, 99, 235, 0.12)' },
  bottomNavIcon: { color: '#6b7280', fontSize: 20, lineHeight: 23, fontWeight: '700' },
  bottomNavIconActive: { color: '#2563eb' },
  bottomNavLabel: { color: '#6b7280', fontSize: 10, fontWeight: '700', marginTop: 2 },
  bottomNavLabelActive: { color: '#1d4ed8' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(17, 24, 39, 0.28)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  modalCard: { width: '100%', backgroundColor: '#ffffff', borderRadius: 10, padding: 20, gap: 14 },
  modalInput: { height: 48, borderWidth: 1, borderColor: '#d1d5db', borderRadius: 6, paddingHorizontal: 12, color: '#111827', fontSize: 16 },
};

const darkColors = {
  background: '#111827',
  surface: '#1f2937',
  surfaceMuted: '#273449',
  text: '#f9fafb',
  textMuted: '#cbd5e1',
  border: '#475569',
  divider: '#334155',
  input: '#111827',
};

export const createStyles = (isDark = false) => {
  if (!isDark) {
    return StyleSheet.create(baseStyles);
  }

  return StyleSheet.create({
    ...baseStyles,
    safeArea: { ...baseStyles.safeArea, backgroundColor: darkColors.background },
    eyebrow: { ...baseStyles.eyebrow, color: '#60a5fa' },
    title: { ...baseStyles.title, color: darkColors.text },
    date: { ...baseStyles.date, color: darkColors.textMuted },
    sectionLabel: { ...baseStyles.sectionLabel, color: darkColors.textMuted },
    progressPercent: { ...baseStyles.progressPercent, color: '#93c5fd' },
    progressTrack: { ...baseStyles.progressTrack, backgroundColor: '#334155' },
    progressLegendText: { ...baseStyles.progressLegendText, color: darkColors.textMuted },
    stat: { ...baseStyles.stat, backgroundColor: darkColors.surface, borderColor: darkColors.border },
    statLabel: { ...baseStyles.statLabel, color: darkColors.textMuted },
    statValue: { ...baseStyles.statValue, color: darkColors.text },
    sectionTitle: { ...baseStyles.sectionTitle, color: darkColors.text },
    muted: { ...baseStyles.muted, color: '#94a3b8' },
    card: { ...baseStyles.card, backgroundColor: darkColors.surface, borderColor: darkColors.border },
    empty: { ...baseStyles.empty, color: '#94a3b8' },
    taskRow: { ...baseStyles.taskRow, borderBottomColor: darkColors.divider },
    taskText: { ...baseStyles.taskText, color: darkColors.textMuted },
    completed: { ...baseStyles.completed, color: '#64748b' },
    workHeader: { ...baseStyles.workHeader, borderBottomColor: darkColors.border },
    workNameHeader: { ...baseStyles.workNameHeader, color: darkColors.textMuted },
    dayHeader: { ...baseStyles.dayHeader, color: darkColors.textMuted },
    workRow: { ...baseStyles.workRow, borderBottomColor: darkColors.divider },
    workName: { ...baseStyles.workName, color: darkColors.textMuted },
    workCheckmark: { ...baseStyles.workCheckmark, borderColor: darkColors.border },
    addRoutinePanel: { ...baseStyles.addRoutinePanel, backgroundColor: darkColors.surfaceMuted },
    addRoutineLabel: { ...baseStyles.addRoutineLabel, color: darkColors.text },
    themeToggleText: { ...baseStyles.themeToggleText },
    inlineInput: { ...baseStyles.inlineInput, backgroundColor: darkColors.input, borderColor: darkColors.border, color: darkColors.text },
    rulesInput: { ...baseStyles.rulesInput, backgroundColor: darkColors.input, borderColor: darkColors.border, color: darkColors.text },
    goalRow: { ...baseStyles.goalRow, borderBottomColor: darkColors.divider },
    goalChip: { ...baseStyles.goalChip, borderColor: '#64748b' },
    selectedGoal: { ...baseStyles.selectedGoal, backgroundColor: '#263b5c' },
    goalText: { ...baseStyles.goalText, color: darkColors.textMuted },
    ruleLabel: { ...baseStyles.ruleLabel, color: darkColors.textMuted },
    smallButton: { ...baseStyles.smallButton, backgroundColor: '#263b5c' },
    smallButtonText: { ...baseStyles.smallButtonText, color: '#bfdbfe' },
    bottomNav: { ...baseStyles.bottomNav, backgroundColor: 'rgba(31, 41, 55, 0.94)', borderColor: '#475569' },
    bottomNavIcon: { ...baseStyles.bottomNavIcon, color: '#cbd5e1' },
    bottomNavLabel: { ...baseStyles.bottomNavLabel, color: '#cbd5e1' },
    modalBackdrop: { ...baseStyles.modalBackdrop, backgroundColor: 'rgba(0, 0, 0, 0.58)' },
    modalCard: { ...baseStyles.modalCard, backgroundColor: darkColors.surface },
    modalInput: { ...baseStyles.modalInput, backgroundColor: darkColors.input, borderColor: darkColors.border, color: darkColors.text },
  });
};
