import { StyleSheet } from 'react-native';

const inkPencil = '#222733';
const pencilLine = '#2b303c';
const bgDesk = '#f3eee3';
const bgPaper = '#fcfbf7';

const baseStyles = {
  safeArea: {
    flex: 1,
    backgroundColor: bgDesk,
  },
  container: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 130,
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  headerContent: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  eyebrow: {
    color: '#2563eb',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.4,
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  title: {
    color: inkPencil,
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  titleMarker: {
    height: 6,
    backgroundColor: '#fef08a',
    marginTop: -4,
    borderRadius: 3,
    width: 140,
  },
  date: {
    flexShrink: 0,
    backgroundColor: '#fef08a',
    borderWidth: 1.8,
    borderColor: pencilLine,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: '#713f12',
    fontSize: 12,
    fontWeight: '800',
    transform: [{ rotate: '1.5deg' }],
    shadowColor: inkPencil,
    shadowOffset: { width: 1.5, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 0,
    elevation: 2,
  },
  pageIntro: {
    marginBottom: 16,
  },
  pagePager: {
    flex: 1,
  },
  page: {
    flex: 1,
  },
  pageContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 120,
    backgroundColor: bgPaper,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 2,
    borderColor: pencilLine,
    borderBottomWidth: 0,
    marginHorizontal: 8,
    shadowColor: inkPencil,
    shadowOffset: { width: 2, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  progressPercent: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '800',
  },
  progressTrack: {
    flexDirection: 'row',
    height: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    borderWidth: 1.8,
    borderColor: pencilLine,
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 6,
  },
  progressHalf: {
    flex: 1,
    overflow: 'hidden',
  },
  progressDivider: {
    width: 2,
    backgroundColor: pencilLine,
  },
  progressValue: {
    height: '100%',
  },
  tasksProgress: {
    backgroundColor: '#0284c7',
  },
  completionProgress: {
    backgroundColor: '#16a34a',
  },
  progressLegend: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  progressLegendText: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  stat: {
    flex: 1,
    padding: 12,
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    shadowColor: inkPencil,
    shadowOffset: { width: 2.5, height: 3.5 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 3,
  },
  statOrange: {
    backgroundColor: '#fff7ed',
    transform: [{ rotate: '-0.8deg' }],
  },
  statYellow: {
    backgroundColor: '#fefce8',
    transform: [{ rotate: '0.9deg' }],
  },
  statBlue: {
    backgroundColor: '#f0f9ff',
    transform: [{ rotate: '-0.5deg' }],
  },
  statGreen: {
    backgroundColor: '#f0fdf4',
    transform: [{ rotate: '0.7deg' }],
  },
  statLabel: {
    color: '#64748b',
    fontSize: 9.5,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  statValue: {
    color: inkPencil,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    color: inkPencil,
    fontSize: 19,
    fontWeight: '900',
  },
  muted: {
    color: '#8d95a5',
    fontSize: 12,
    fontWeight: '600',
  },
  card: {
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
    backgroundColor: '#ffffff',
    shadowColor: inkPencil,
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 3,
    transform: [{ rotate: '-0.3deg' }],
  },
  empty: {
    color: '#8d95a5',
    fontSize: 13,
    fontWeight: '600',
    paddingVertical: 12,
    textAlign: 'center',
  },
  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingVertical: 6,
    borderBottomWidth: 1.5,
    borderBottomColor: '#f1f5f9',
    borderStyle: 'dashed',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#ffffff',
    transform: [{ rotate: '-2deg' }],
  },
  checked: {
    backgroundColor: '#dcfce7',
    borderColor: '#16a34a',
  },
  checkmark: {
    color: '#16a34a',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 17,
  },
  taskText: {
    flex: 1,
    minWidth: 0,
    color: inkPencil,
    fontSize: 15,
    fontWeight: '600',
  },
  completed: {
    color: '#8d95a5',
    textDecorationLine: 'line-through',
  },
  workBoard: {
    marginBottom: 18,
    paddingVertical: 4,
  },
  addRoutinePanel: {
    backgroundColor: '#fefce8',
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 14,
    padding: 14,
    marginBottom: 24,
    shadowColor: inkPencil,
    shadowOffset: { width: 2.5, height: 3.5 },
    shadowOpacity: 0.75,
    shadowRadius: 0,
    elevation: 3,
    transform: [{ rotate: '0.4deg' }],
  },
  addRoutineLabel: {
    color: '#713f12',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginBottom: 9,
    textTransform: 'uppercase',
  },
  themeToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    marginBottom: 18,
  },
  themeToggleText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  delete: {
    color: '#94a3b8',
    fontSize: 20,
    fontWeight: '700',
    paddingHorizontal: 8,
  },
  workScroller: {
    flexGrow: 0,
    flexShrink: 0,
  },
  workTable: {
    minWidth: 420,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 14,
    padding: 10,
    shadowColor: inkPencil,
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 3,
  },
  workHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: pencilLine,
    minHeight: 36,
    paddingBottom: 4,
    backgroundColor: '#f8f6ee',
    borderRadius: 8,
    paddingHorizontal: 6,
  },
  workNameHeader: {
    width: 140,
    color: '#64748b',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  dayHeader: {
    width: 36,
    color: '#4b5563',
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  workDeleteHeader: {
    width: 28,
  },
  workRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    borderBottomWidth: 1.2,
    borderBottomColor: '#cbd5e1',
    borderStyle: 'dashed',
    paddingHorizontal: 6,
  },
  workName: {
    width: 140,
    flexShrink: 1,
    color: inkPencil,
    fontSize: 13.5,
    fontWeight: '700',
  },
  workCheckboxCell: {
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  workCheckmark: {
    width: 20,
    height: 20,
    borderWidth: 1.8,
    borderColor: pencilLine,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  workCheckText: {
    color: '#16a34a',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 14,
  },
  workChecked: {
    backgroundColor: '#dcfce7',
    borderColor: '#16a34a',
  },
  workDelete: {
    width: 28,
    alignItems: 'center',
  },
  addWorkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  inlineInput: {
    flex: 1,
    height: 44,
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 10,
    paddingHorizontal: 12,
    color: inkPencil,
    fontSize: 14,
    fontWeight: '600',
    backgroundColor: '#ffffff',
  },
  rulesInput: {
    width: '100%',
    height: 50,
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 10,
    paddingHorizontal: 14,
    color: inkPencil,
    backgroundColor: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 14,
  },
  smallButton: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: pencilLine,
    paddingHorizontal: 16,
    height: 44,
    justifyContent: 'center',
    shadowColor: inkPencil,
    shadowOffset: { width: 1.5, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
    elevation: 2,
  },
  smallButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 13,
  },
  goalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingVertical: 8,
    borderBottomWidth: 1.5,
    borderBottomColor: '#f1f5f9',
    borderStyle: 'dashed',
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  selectedGoal: {
    backgroundColor: '#eff6ff',
    borderWidth: 1.5,
    borderColor: '#3b82f6',
  },
  goalScroller: {
    flexGrow: 0,
    flexShrink: 0,
    marginBottom: 12,
  },
  goalChip: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 34,
    borderWidth: 1.8,
    borderColor: pencilLine,
    borderRadius: 17,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
    marginRight: 8,
    shadowColor: inkPencil,
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 0,
    elevation: 2,
  },
  goalList: {
    alignItems: 'center',
    paddingVertical: 2,
  },
  goalDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: pencilLine,
    marginRight: 8,
  },
  goalText: {
    color: inkPencil,
    fontSize: 13.5,
    fontWeight: '700',
  },
  chevron: {
    color: '#94a3b8',
    fontSize: 20,
    fontWeight: '700',
  },
  ruleLabel: {
    color: inkPencil,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
    marginTop: 4,
  },
  primaryButton: {
    backgroundColor: '#2563eb',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: pencilLine,
    alignItems: 'center',
    paddingVertical: 13,
    shadowColor: inkPencil,
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 3,
  },
  rulesButton: {
    marginTop: 10,
  },
  savedMessage: {
    color: '#15803d',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 10,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 15,
  },
  floatingButton: {
    position: 'absolute',
    right: 22,
    bottom: 96,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2563eb',
    borderWidth: 2.5,
    borderColor: pencilLine,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: inkPencil,
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.9,
    shadowRadius: 0,
    elevation: 6,
    transform: [{ rotate: '-3deg' }],
  },
  floatingPlus: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 34,
  },
  bottomNavShell: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 14,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: pencilLine,
    backgroundColor: '#ffffff',
    shadowColor: inkPencil,
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.88,
    shadowRadius: 0,
    elevation: 8,
    overflow: 'hidden',
  },
  bottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    minHeight: 64,
    paddingHorizontal: 8,
    backgroundColor: '#ffffff',
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    borderRadius: 14,
  },
  bottomNavItemActive: {
    backgroundColor: '#fef08a',
    borderWidth: 1.5,
    borderColor: pencilLine,
    transform: [{ translateY: -2 }],
  },
  bottomNavIcon: {
    color: '#64748b',
    fontSize: 19,
    lineHeight: 22,
    fontWeight: '800',
  },
  bottomNavIconActive: {
    color: '#713f12',
  },
  bottomNavLabel: {
    color: '#64748b',
    fontSize: 10.5,
    fontWeight: '800',
    marginTop: 2,
  },
  bottomNavLabelActive: {
    color: '#713f12',
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 2.2,
    borderColor: pencilLine,
    padding: 22,
    gap: 14,
    shadowColor: inkPencil,
    shadowOffset: { width: 4, height: 5 },
    shadowOpacity: 0.9,
    shadowRadius: 0,
    elevation: 8,
  },
  modalInput: {
    height: 50,
    borderWidth: 2,
    borderColor: pencilLine,
    borderRadius: 10,
    paddingHorizontal: 14,
    color: inkPencil,
    fontSize: 15,
    fontWeight: '600',
  },
};

const darkColors = {
  background: '#181b22',
  paper: '#222733',
  surface: '#2c3342',
  surfaceMuted: '#374154',
  text: '#f8fafc',
  textMuted: '#94a3b8',
  border: '#475569',
  divider: '#334155',
  input: '#1e2430',
};

export const createStyles = (isDark = false) => {
  if (!isDark) {
    return StyleSheet.create(baseStyles);
  }

  return StyleSheet.create({
    ...baseStyles,
    safeArea: { ...baseStyles.safeArea, backgroundColor: darkColors.background },
    pageContainer: {
      ...baseStyles.pageContainer,
      backgroundColor: darkColors.paper,
      borderColor: darkColors.border,
    },
    title: { ...baseStyles.title, color: darkColors.text },
    eyebrow: { ...baseStyles.eyebrow, color: '#60a5fa' },
    date: {
      ...baseStyles.date,
      backgroundColor: '#ca8a04',
      color: '#fefce8',
      borderColor: darkColors.border,
    },
    stat: {
      ...baseStyles.stat,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    statLabel: { ...baseStyles.statLabel, color: darkColors.textMuted },
    statValue: { ...baseStyles.statValue, color: darkColors.text },
    sectionTitle: { ...baseStyles.sectionTitle, color: darkColors.text },
    card: {
      ...baseStyles.card,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    taskRow: { ...baseStyles.taskRow, borderBottomColor: darkColors.divider },
    checkbox: {
      ...baseStyles.checkbox,
      backgroundColor: darkColors.surfaceMuted,
      borderColor: darkColors.border,
    },
    taskText: { ...baseStyles.taskText, color: darkColors.text },
    bottomNavShell: {
      ...baseStyles.bottomNavShell,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    bottomNav: { ...baseStyles.bottomNav, backgroundColor: darkColors.surface },
    bottomNavItemActive: {
      ...baseStyles.bottomNavItemActive,
      backgroundColor: '#3b82f6',
      borderColor: '#60a5fa',
    },
    bottomNavIconActive: { color: '#ffffff' },
    bottomNavLabelActive: { color: '#ffffff' },
    modalCard: {
      ...baseStyles.modalCard,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    modalInput: {
      ...baseStyles.modalInput,
      backgroundColor: darkColors.input,
      color: darkColors.text,
      borderColor: darkColors.border,
    },
    inlineInput: {
      ...baseStyles.inlineInput,
      backgroundColor: darkColors.input,
      color: darkColors.text,
      borderColor: darkColors.border,
    },
    rulesInput: {
      ...baseStyles.rulesInput,
      backgroundColor: darkColors.input,
      color: darkColors.text,
      borderColor: darkColors.border,
    },
    workTable: {
      ...baseStyles.workTable,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    workHeader: {
      ...baseStyles.workHeader,
      backgroundColor: darkColors.surfaceMuted,
      borderBottomColor: darkColors.border,
    },
    workRow: {
      ...baseStyles.workRow,
      borderBottomColor: darkColors.divider,
    },
    workName: { ...baseStyles.workName, color: darkColors.text },
    goalChip: {
      ...baseStyles.goalChip,
      backgroundColor: darkColors.surface,
      borderColor: darkColors.border,
    },
    goalText: { ...baseStyles.goalText, color: darkColors.text },
  });
};
